update script infrastructure to latest state

diff --git a/bin/websearch b/bin/websearch
--- a/bin/websearch
+++ b/bin/websearch
@@ -1,31 +1,21 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-#set -x
+set -o errexit  # abort when any commands exits with error
+# set -o pipefail # abort when any command in a pipe exits with error
+set -o nounset  # abort when any unset variable is used
+set -f # prevent bash from expanding glob
+trap 'echo "$0: line ${LINENO}: exiting because of error";exit 1' ERR
 
-function getOptions() {
-  while getopts "idsl:h:p:" options; do
-    case $options in
-      p )
-        W3M_PARAMETERS="$OPTARG"
-        ;;
-      i )
-        SEARCH_HOST="ixquick.com"
-        ;;
-      l )
-        LIMIT="$OPTARG"
-        ;;
-      h )
-        HOST="host:$OPTARG "
-        ;;
-      s )
-        STDOUT_PRINT="1"
-        ;;
-      d )
-        DRY_RUN="1"
-        ;;
-      \? )
-        echo "HELP"
-        echo "host:stackoverflow.com +java +method -chain
+while getopts "idsl:h:p:" options; do case $options in
+  p ) W3M_PARAMETERS="$OPTARG" ;;
+  i ) SEARCH_HOST="ixquick.com" ;;
+  l ) LIMIT="$OPTARG" ;;
+  h ) HOST="host:$OPTARG " ;;
+  s ) STDOUT_PRINT="1" ;;
+  d ) DRY_RUN="1" ;;
+  \? )
+    echo "HELP"
+    echo "host:stackoverflow.com +java +method -chain
 host:stackoverflow.com 'java method'
 (java OR method OR chain)
 java AND (kodkdkjfkdj OR hello)
@@ -33,29 +23,27 @@ java ANDNOT hello
 java NOT hello"
         exit 1
         ;;
-    esac
-  done
-  PARSED_OPT_COUNT=$OPTIND
-}
+esac; done; shift $((OPTIND - 1))
 
-getOptions $@
-shift $(( PARSED_OPT_COUNT - 1 ));
+[[ -r ~/.$(basename ${0})rc ]] && { source ~/.$(basename ${0})rc; }
+
+: ${DRY_RUN:=""}
+: ${LIMIT:=10}
+: ${SEARCH_HOST:="startpage.com"}
+: ${HOST:=""}
+: ${STDOUT_PRINT:=""}
+: ${W3M_PARAMETERS:=""}
 
 ORIGINAL_QUERY=$@
 QUERY=$( echo "$ORIGINAL_QUERY" |  tr "'" '"')
-if [ -n "$DRY_RUN" ];then
-  echo "$ORIGINAL_QUERY"
-  echo "$QUERY"
-fi
-
-: ${LIMIT:=10}
-: ${SEARCH_HOST:="startpage.com"}
 
 PRFH="prfh=lang_homepageEEEs%2Fwhite%2Feng%2FN1Nfont_sizeEEEmediumN1Nrecent_results_filterEEE1N1Nlanguage_uiEEEenglishN1Nsearch_engine_sourcesEEE1N1Ndisable_open_in_new_windowEEE0N1NsslEEE1N1Nnum_of_resultsEEE${LIMIT}N1N"
 DEFAULT_VALUES="cat=web&cmd=process_search&language=english&engine0=v1all&x=12&y=24" 
 POST_QUERIES="${PRFH}&${DEFAULT_VALUES}&query=$(urlencode "${HOST}${QUERY}")"
 
 if [ -n "$DRY_RUN" ];then
+  echo "$ORIGINAL_QUERY"
+  echo "$QUERY"
   echo "HOST:https://${SEARCH_HOST}/do/metasearch.pl" 1>&2
   echo "BODY:$POST_QUERIES" 1>&2
   exit 0
@@ -82,6 +70,7 @@ BODY=$( \
     -e 's/\(<span class="desc\)/<br\/>\1/g' \
     -e '/^ *onclick=".*"$/d' \
     -e '/^ *$/d' \
+|| true
 )
 
 if [ -n "$STDOUT_PRINT" ];then
